#!/bin/bash

# -------------------------------------------------------------------------- #
# OpenNebula Marketplace Driver - cozyportal                                 #
#                                                                            #
# Copyright 2026, Aenix (aenix.io).                                          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
# -------------------------------------------------------------------------- #

###############################################################################
# Report marketplace storage metrics to OpenNebula.
#
# The Cozyportal Files API does not expose per-marketplace quotas: storage
# accounting happens at the S3 bucket level, owned by the Cozyportal operator.
# We report a fixed synthetic capacity so OpenNebula can display the market
# as healthy. Numbers are not load-bearing for scheduling.
###############################################################################

# Values are in MB and can be overridden via cozyportal.conf.
TOTAL_MB="${COZYPORTAL_TOTAL_MB:-1048576}"
USED_MB="${COZYPORTAL_USED_MB:-0}"
FREE_MB=$((TOTAL_MB - USED_MB))

echo "USED_MB=$USED_MB"
echo "FREE_MB=$FREE_MB"
echo "TOTAL_MB=$TOTAL_MB"
